---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: external-via-gcp-sm
  namespace: MY_NAMESPACE
spec:
  provider:
    gcpsm:
      auth:
        workloadIdentity:
          clusterLocation: "MY_GCP_REGION"
          clusterName: "MY_CLUSTER_NAME"
          clusterProjectID: "MY_PROJECT_ID"
          serviceAccountRef:
            name: "MY_SECRET_MANAGER_SA_NAME"
      projectID: "MY_PROJECT_ID"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: facebook-token-gcp-sm
spec:
  refreshInterval: 1h
  # Needs to be a reference from the resource above
  secretStoreRef:
    name: external-via-gcp-sm
    kind: SecretStore
  # This will be the Secret resource name within K8s
  target:
    name: facebook-token
    creationPolicy: Owner
  data:
    # the Secret key name for the resource
  - secretKey: MY_SECRET_NAME
    remoteRef:
      key: MY_SECRET_NAME
      #version: provider-key-version
      #property: provider-key-property
  #dataFrom:
  #- extract:
  #    key: remote-key-in-the-provider
