---
# Handler to handle restart notifications

- name: Systemd restart prometheus
  listen: "restart prometheus"
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Systemd restart nginx
  listen: "reload nginx"
  ansible.builtin.systemd:
    name: nginx.service
    state: reloaded
    daemon_reload: yes
    enabled: yes