---
- name: Update apt cache if needed.
  apt:
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"

- name: Upgrade all packages to the latest version.
  apt:
    name: "*"
    state: latest
    cache_valid_time: "{{ aptcachetime }}"

- name: Install required packages for HTTPS repositories.
  apt: 
    pkg: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "gnupg"] 
    state: latest 
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
