---
# HINT: You need to execute 'kubernetes.yml' because it imports the same keyring that this repository needs.

- name: Add GCP Debian repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by={{ kubernetes_gpg_key }}] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    update_cache: yes
    filename: "google-cloud-platform"

- name: Install google-cloud-cli package
  apt:
    pkg: ["google-cloud-cli"]
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
