---
# HINT: curl -s https://apt.releases.hashicorp.com/gpg | gpg --armor
# pub   rsa4096 2023-01-10 [SC] [expires: 2028-01-09]
#       798AEC654E5C15428C8E42EEAA16FCBCA621E701
# uid           HashiCorp Security (HashiCorp Package Signing) <security+packaging@hashicorp.com>
# sub   rsa4096 2023-01-10 [S] [expires: 2028-01-09]

- name: Installing HashiCorp keyring
  ansible.builtin.apt_key:
    state: present
    id: "798AEC654E5C15428C8E42EEAA16FCBCA621E701"
    url: https://apt.releases.hashicorp.com/gpg
    keyring: "{{ hashicorp_gpg_key }}"

- name: Add HashiCorp repository
  ansible.builtin.apt_repository: 
    repo: "deb [signed-by={{ hashicorp_gpg_key }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
    filename: "hashicorp.list"

- name: Install Terraform package
  apt: 
    pkg: ["terraform"]
    state: "{{ hashicorp.terraform_version }}"
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
