---
# HINT: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --armor
# pub   rsa2048 2021-03-01 [SC] [expires: 2023-03-02]
#       7F92E05B31093BEF5A3C2D38FEEA9169307EA071
# uid           Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)
# sub   rsa2048 2021-03-01 [E]
# pub   rsa2048 2020-12-04 [SC] [expires: 2022-12-04]
#       59FE0256827269DC81578F928B57C5C2836F4BEB
# uid           gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>
# sub   rsa2048 2020-12-04 [E]

- name: Installing GCP keyring
  ansible.builtin.apt_key:
    state: present
    id: "7F92E05B31093BEF5A3C2D38FEEA9169307EA071"
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: "{{ kubernetes_gpg_key }}"

- name: Add Kubernetes Debian repository
  ansible.builtin.apt_repository: 
    repo: "deb [arch=amd64 signed-by={{ kubernetes_gpg_key }}] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    update_cache: yes
    filename: "kubernetes.list"

- name: Install Kubectl package
  apt: 
    pkg: ["kubectl"]
    state: "{{ kubernetes.cli_version }}"
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"

- name: "Install k3d binary on {{ kubernetes.k3d_version }} release"
  ansible.builtin.get_url:
    url: "https://github.com/k3d-io/k3d/releases/download/v{{ kubernetes.k3d_version }}/k3d-linux-amd64"
    dest: "/usr/local/bin/k3d"
    owner: "root"
    group: "root"
    mode: "0755"

# HINT: It's better to always install the latest release because it is always improving
- name: "Install skaffold binary on latest release"
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64"
    dest: "/usr/local/bin/skaffold"
    owner: "root"
    group: "root"
    mode: "0755"
