all:
#  hosts:
#    mail.example.com:
  children:
    ubuntu:
      hosts:
        440a1038311c.mylabserver.com:
    monitoring_server:
      hosts:
        440a1038311c.mylabserver.com:
    monitoring_client:
      hosts:
        440a1038312c.mylabserver.com:
