apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: MY_SECRET_NAME
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/MY_PROJECT_ID/secrets/MY_SECRET_NAME/versions/latest"
        path: "MY_SECRET_NAME.txt"
