---
- name: "Add group {{ prometheus.user_settings.group }}, with GID as {{ prometheus.user_settings.gid }}, as a system group"  
  ansible.builtin.group:
    name: "{{ prometheus.user_settings.group }}"
    gid: "{{ prometheus.user_settings.gid }}"
    system: true

- name: "Add user {{ prometheus.user_settings.user }}, with UID/Group as {{ prometheus.user_settings.uid }}/{{ prometheus.user_settings.group }} as system user"  
  ansible.builtin.user:
    name: "{{ prometheus.user_settings.user }}"
    comment: "Prometheus service"
    uid: "{{ prometheus.user_settings.uid }}"
    group: "{{ prometheus.user_settings.group }}"
    create_home: false
    shell: /usr/bin/false
    system: true


- name: "Decompress Prometheus {{ prometheus.version }} release from GitHub"
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus.version }}/prometheus-{{ prometheus.version }}.linux-{{ deb_architecture[ansible_architecture] }}.tar.gz"
    dest: "/opt/"
    owner: "{{ prometheus.user_settings.user }}"
    group: "{{ prometheus.user_settings.group }}"
    mode: 0755
    remote_src: yes

- name: "Assign Prometheus {{ prometheus.version }} release as current Prometheus"
  ansible.builtin.file:
    src: "{{ prometheus_release_dir }}"
    dest: "{{ prometheus.working_dir }}"
    owner: "{{ prometheus.user_settings.user }}"
    group: "{{ prometheus.user_settings.group }}"
    state: link

- name: "Create multiple default directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus.user_settings.user }}"
    group: "{{ prometheus.user_settings.group }}"
    mode: 0775
  loop:
    - "{{ prometheus.var_dir }}"
    - "{{ prometheus.cfg_dir }}"

- name: "Symlink Prometheus binaries from {{ prometheus.working_dir }}"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ prometheus.user_settings.user }}"
    group: "{{ prometheus.user_settings.group }}"
    state: link
  with_items:
    - { src: "{{ prometheus.working_dir }}/prometheus", dest: "{{ prometheus.bin_dir }}/prometheus" }
    - { src: "{{ prometheus.working_dir }}/promtool", dest: "{{ prometheus.bin_dir }}/promtool" }

- name: "Symlink Prometheus directories from {{ prometheus.working_dir }}"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ prometheus.user_settings.user }}"
    group: "{{ prometheus.user_settings.group }}"
    state: link
  with_items:
    - { src: "{{ prometheus.working_dir }}/consoles", dest: "{{ prometheus.cfg_dir }}/consoles" }
    - { src: "{{ prometheus.working_dir }}/console_libraries", dest: "{{ prometheus.cfg_dir }}/console_libraries" }
    - { src: "{{ prometheus.working_dir }}/prometheus.yml", dest: "{{ prometheus.cfg_dir }}/prometheus.yml" }


- name: Placing Prometheus systemd init file
  ansible.builtin.template:
    src: prometheus.systemd.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root 
    group: root
    mode: 0644
  notify:
  - restart prometheus

- name: Enabling and starting Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: true

- name: "Allow access to tcp port {{ prometheus.port }} locally"
  ufw:
    rule: allow
    port: "{{ prometheus.port }}"
    proto: tcp
    src: "{{ item }}"
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16

# Continue reading here
# https://www.cherryservers.com/blog/install-prometheus-ubuntu
# https://github.com/in4it/prometheus-course/tree/master/scripts